# Generated by Django 5.1.2 on 2025-02-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
