# Generated by Django 5.1.2 on 2024-12-11 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=25)),
                ('contact_subject', models.CharField(max_length=20)),
                ('contact_dis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usertypeModel',
            fields=[
                ('usertype_id', models.IntegerField(primary_key=True, serialize=False)),
                ('usertype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobileno', models.CharField(blank=True, max_length=15, null=True)),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.usertypemodel')),
            ],
        ),
    ]
