# Generated by Django 5.1.2 on 2024-12-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('contact_id', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=25)),
                ('contact_subject', models.CharField(max_length=20)),
                ('contact_dis', models.CharField(max_length=100)),
            ],
        ),
    ]
