# Generated by Django 5.1.2 on 2025-02-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adhhar_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
