# Generated by Django 5.1.2 on 2024-12-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
    ]
