# Generated by Django 5.1.2 on 2024-12-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='contact_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
