# Generated by Django 5.1.2 on 2024-12-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_user_adhhar_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.IntegerField()),
            ],
        ),
    ]
