# Generated by Django 5.1.2 on 2024-12-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_contactmodel_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='contact_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
