# Generated by Django 5.1.2 on 2025-02-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_user_adhhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adhhar_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
