# Generated by Django 5.1.2 on 2025-04-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_alter_user_adhhar_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
    ]
