# Generated by Django 4.2.16 on 2026-06-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_alter_contactmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertypemodel',
            name='usertype',
            field=models.CharField(max_length=20),
        ),
    ]
