# Generated by Django 5.1.2 on 2025-01-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_age', models.IntegerField()),
                ('gender', models.CharField(max_length=250)),
                ('diagnosis', models.CharField(max_length=255)),
                ('medication', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('prescription_details', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ipd_opd', models.CharField(max_length=255)),
            ],
        ),
    ]
