# Generated by Django 5.1.2 on 2025-01-27 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0001_initial'),
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appointment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.appointment'),
        ),
    ]
