# Generated by Django 5.1.2 on 2025-01-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='problem',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
