# Generated by Django 5.1.2 on 2025-02-09 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('charges', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_no', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Receptionist.patientrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('total_beds', models.IntegerField()),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Receptionist.patientrecord')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receptionist.room_type')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receptionist.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receptionist.patientrecord')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receptionist.room')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Receptionist.room'),
        ),
    ]
