# Generated by Django 5.1.2 on 2025-02-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receptionist', '0003_alter_bed_patient_alter_booking_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='room',
            name='patient',
        ),
    ]
